name: Renders RMD 

on:
  pull_request:
    branches:
      - main
    paths:
      - 'vignettes/OCMSutility.Rmd'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch history to compare file changes

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown

      - name: Install more dependencies
        run: |
          Rscript -e "install.packages(c(‘BiocManager’, ‘dplyr’, ‘DescTools’, ‘foreach’, ‘ggdendro’, ‘ggfortify’, ‘ggplot2’, ‘ggrepel’, ‘gtools’, ‘psych’, ‘readxl’, ‘reshape2’, ‘RColorBrewer’, ‘RSQLite’, ‘tibble’, ‘stringr’, ‘vegan’, dependencies=TRUE)"
          Rscript -e "BiocManager::install(c('ALDEx2', 'phyloseq'))"

      - name: Install OCMSutility
        run: |
         Rscript -e 'install.packages(".", repos=NULL, type="source", dependencies=TRUE)'
  
      - name: Check if OCMSutility.Rmd file has changed
        id: check_changes
        run: |
          FILE_HASH=$(sha256sum vignettes/OCMSutility.Rmd | awk '{print $1}')
          PREV_HASH=$(git show origin/${{ github.base_ref }}:vignettes/OCMSutility.Rmd 2>/dev/null | sha256sum | awk '{print $1}' || echo "")
          if [ "$FILE_HASH" != "$PREV_HASH" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Update README
        if: ${{ env.changed == 'true' }}
        run: |
          Rscript -e 'rmarkdown::render("vignettes/OCMSutility.Rmd", output_format = "md_document", output_options = list(pandoc_args = c("-t", "gfm")))'
          Rscript -e 'file <- gsub("\\.\\./inst", "inst", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
          Rscript -e 'file <- gsub("OCMSutility_files", "vignettes/OCMSutility_files", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
          Rscript -e 'file <- gsub("\\((.*)\\.([rR]md)","(vignettes/\\1.\\2", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
          Rscript -e 'file.copy("vignettes/OCMSutility.md", "README.md", overwrite = TRUE)'
          Rscript -e 'suppressWarnings(file.remove("vignettes/OCMSutlity.md"))'

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README files" || echo "No changes to commit"
          git push