name: Renders RMD 

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'vignettes/OCMSutility.Rmd'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
      
      - name: Update  README
        if: hashFiles('vignettes/OCMSutility.Rmd') != ''
        run: |
	  Rscript -e 'rmarkdown::render("vignettes/OCMSutility.Rmd", output_format = "md_document", output_options = list(pandoc_args = c("-t", "gfm")))'
	  Rscript -e 'file <- gsub("\\.\\./inst", "inst", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
	  Rscript -e 'file <- gsub("OCMSutility_files", "vignettes/OCMSutility_files", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
	  Rscript -e 'file <- gsub("\\((.*)\\.([rR]md)","(vignettes/\\1.\\2", readLines("vignettes/OCMSutility.md")); writeLines(file, "vignettes/OCMSutility.md")'
	  Rscript -e 'file.copy("vignettes/OCMSutility.md", "README.md", overwrite = TRUE)'
	  Rscript -e 'suppressWarnings(file.remove("vignettes/OCMSutlity.md"))'
      - name: Commit changes
        run: |
	  git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README files" || echo "No changes to commit"
          git push